live_config_reload = true
working_directory = "None"

import = ["~/.config/alacritty/github_dark_dimmed.toml"]

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 1000

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
blink_interval = 750
vi_mode_style = "None"
thickness = 0.15
unfocused_hollow = true
style.blinking = "On"
style.shape = "Block"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "Buttonless"
dynamic_title = true
opacity = 0.85
startup_mode = "Maximized"
